In [1]:
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentence=
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understant the meaning of words',
    'your videos are good',

]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understant the meaning of words',
 'your videos are good']

In [4]:
## we neeed to define the vocabuloury size
voc_size=10000

In [5]:
## one_hot representation of every word
one_hot_rpr=[one_hot(words, voc_size)for words in sent]

In [6]:
one_hot_rpr

[[2287, 5327, 1485, 1642],
 [2287, 5327, 1485, 5686],
 [2287, 7755, 1485, 8192],
 [2473, 6259, 2048, 7839, 3160],
 [2473, 6259, 2048, 7839, 626],
 [1180, 2287, 8198, 1485, 2342],
 [5740, 4506, 8544, 7839]]

In [7]:
# one_hot_rpr = []
# for words in sent:
#     encoded_words = one_hot(words, voc_size)
#     one_hot_rpr.append(encoded_words)

# one_hot_rpr

In [ ]:
import tensorflow as tf
# print(tf.__version__)


8

In [9]:
## word embeddingb representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np


In [66]:
sent_length=8
one_hot_rpr = [one_hot(words, voc_size) for words in sent]
embedded_docs = pad_sequences(one_hot_rpr, padding='pre', maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 2287 5327 1485 1642]
 [   0    0    0    0 2287 5327 1485 5686]
 [   0    0    0    0 2287 7755 1485 8192]
 [   0    0    0 2473 6259 2048 7839 3160]
 [   0    0    0 2473 6259 2048 7839  626]
 [   0    0    0 1180 2287 8198 1485 2342]
 [   0    0    0    0 5740 4506 8544 7839]]


In [42]:
## festure reprenstation
dim=10

In [67]:
dim, voc_size, sent_length

(10, 10000, 8)

In [68]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')
 # This forces the model to build


d:\python\deep learning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [69]:
model.summary()

Model: "sequential_26"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_30 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [86]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Example Parameters
voc_size = 10000  # Vocabulary size
dim = 10         # Embedding dimensions
sent_length = 8  # Maximum sentence length

# Sample input data

one_hot_rpr = [one_hot(words, voc_size) for words in sent]
embedded_docs = pad_sequences(one_hot_rpr, padding='pre', maxlen=sent_length)

# Model Definition
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')


# Make prediction
predictions = model.predict(embedded_docs)
model.summary()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


Model: "sequential_34"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_38 (Embedding)        │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [87]:
predictions = model.predict(embedded_docs)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[[-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.00658915  0.04582271 -0.02644706 -0.01048678  0.03637138
   -0.03989167  0.04005451  0.00087429  0.0447976  -0.00585743]
  [ 0.00036192  0.01612816 -0.00611817 -0.02337911 -0.02481499
    0.03958592 -0.04729197 -0.0399524   0.03414967 -0.04837588]
  [ 0.01534684  0.00980027 -0.00316089 -0.03258036  0.02572112
    0.00107576 -0.02151345 -0.00464147 -0.0267361  -0.00737701]
  [-0.01299536 -0.00529871  0.01510835 -0.03102299  0.03051754
    0.0363

In [88]:
embedded_docs[0]

array([   0,    0,    0,    0, 2287, 5327, 1485, 1642])

In [92]:
input_data = np.expand_dims(embedded_docs[0], axis=0)

# Now make the prediction
predictions = model.predict(input_data)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[[-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.04479643  0.02844019  0.01287934 -0.02897902  0.00014589
   -0.02028159  0.01527867 -0.01179198  0.03819628  0.04524389]
  [-0.00658915  0.04582271 -0.02644706 -0.01048678  0.03637138
   -0.03989167  0.04005451  0.00087429  0.0447976  -0.00585743]
  [ 0.00036192  0.01612816 -0.00611817 -0.02337911 -0.02481499
    0.03958592 -0.04729197 -0.0399524   0.03414967 -0.04837588]
  [ 0.01534684  0.00980027 -0.00316089 -0.03258036  0.02572112
    0.00107576 -0.02151345 -0.00464147 -0.0267361  -0.00737701]
  [-0.01299536 -0.00529871  0.01510835 -0.03102299  0.03051754
    0.0363